descartes_bi/apps/common/urls.py
from django.conf import settings
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from django.views.generic.base import RedirectView

from .views import AboutView, HomeView

urlpatterns = patterns('common.views',
    url(r'^$', login_required(HomeView.as_view()), name='home_view'),
    url(r'^set_language/$', 'set_language', name='set_language'),
    url(r'^about/$', login_required(AboutView.as_view()), name='about_view'),
)

urlpatterns += patterns('',
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'core/login.html'}, name='login_view'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': 'common:home_view'}, name='logout_view'),
    url(r'^myaccount/password_change/$', 'django.contrib.auth.views.password_change', {'template_name': 'core/password_change_form.html'}, name='password_change_view'),
    url(r'^accounts/password_change_ok/$', 'django.contrib.auth.views.password_change_done', {'template_name': 'core/password_change_done.html'}),

    (r'^favicon\.ico$', RedirectView.as_view(url='%simages/favicon.png' % settings.STATIC_URL)),
)

descartes_bi/urls.py
from django.conf.urls import include, patterns, url
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

handler500 = 'common.views.error500'
urlpatterns = patterns('',
    (r'^', include('common.urls', namespace='common')),
    (r'^admin/', include(admin.site.urls)),
    (r'^dashboards/', include('dashboards.urls', namespace='dashboards')),
    (r'^widgets/', include('widgets.urls', namespace='widgets')),
)

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    if 'rosetta' in settings.INSTALLED_APPS:
        urlpatterns += patterns('',
            url(r'^rosetta/', include('rosetta.urls'), name='rosetta'),
        )

descartes_bi/apps/core/templates/core/about.html
{% extends 'core/base.html' %}

{% load i18n %}
{% load static %}

{% load project_tags %}

{% block title %} :: {% trans 'About this program' %}{% endblock %}
{% block banner %}{% trans 'About this program' %}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3 text-center">
            <img class="img-responsive center-block" src="{% static 'core/images/logo.png' %}" alt="{% trans 'logo' %}" />
            <h1><strong>{% project_name %}</strong></h1>
            <h2><strong>{% trans 'Free Open Source web based business intelligence software' %}</strong></h2>
            <a href="http://github.com/rosarior/descartes-bi">{% trans 'http://github.com/rosarior/descartes-bi' %}</a><br>
            {% trans 'Copyright (C) 2010 Roberto Rosario' %}<br />
            {% trans 'Released under the Apache 2.0 License' %}<br />
            {% trans 'Made with <i class="fa fa-heart heart"></i> in Puerto Rico' %}
        </div>
    </div>
{% endblock content %}

descartes_bi/apps/core/templates/core/base.html
{% load i18n %}
{% load static %}

{% load compress %}

{% load project_tags %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <title>{% project_name %}{% block title %}{% endblock %}</title>

        {% compress css %}
            <link href="{% static 'core/packages/bootstrap-3.2.0-dist/css/bootstrap.min.css' %}" rel="stylesheet">
            <link href="{% static 'core/packages/font-awesome-4.1.0/css/font-awesome.min.css' %}" rel="stylesheet">
            <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
            <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
            <!--[if lt IE 9]>
              <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
              <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
            <![endif]-->

            <link href="//fonts.googleapis.com/css?family=Raleway:100,200,300,400,500,600,700,800,900" rel="stylesheet" type="text/css">

            <style>
                html {
                    background: url("{% static 'core/images/backgrounds/ocean.jpg' %}") no-repeat center center fixed;
                    -webkit-background-size: cover;
                    -moz-background-size: cover;
                    -o-background-size: cover;
                    background-size: cover;
                }

                body {
                    background: rgba(0, 0, 0, 0);
                    color: white;
                    text-shadow: 1px 1px 3px rgba(0,0,0,.5);
                    font-family: 'Raleway';
                }

                .navbar {
                    background: rgba(0, 0, 0, 0.1);
                    margin-bottom: 10px;
                    color: white;
                }

                .navbar-inverse .navbar-nav>li>a {
                    color: #eee;
                }

                .navbar-inverse .navbar-brand {
                    color: #eee;
                }

                .navbar-nav>li>.dropdown-menu {
                    background: rgba(0, 0, 0, 0.6);
                    -moz-box-shadow: 0 0 8px black;
                    -webkit-box-shadow: 0 0 8px black;
                    box-shadow: 0 0 8px black;
                }

                .dropdown-menu>li>a {
                    color: white;
                }

                a {
                    color: white;
                }

                a:hover {
                    color: yellow;
                }

                @media (min-width: 768px) {
                    .navbar-nav{
                        margin: 0 auto;
                        display: table;
                        table-layout: fixed;
                        float: none;
                    }
                    #main-navigation {
                        float: right
                    }
                }

                .widget {
                    background: rgba(0, 0, 0, 0.1);
                    box-shadow: 0 0 5px rgba(0, 0, 0, 0.15);
                    margin-top: 10px;
                    margin-bottom: 10px;
                }
                .widget:hover {
                    background-color: rgba(155, 155, 155, 0.1);
                    -moz-box-shadow: 3px 3px 2px 0px #151515;
                    -webkit-box-shadow: 3px 3px 2px 0px #151515;
                    box-shadow: 3px 3px 2px 0px #151515;
                }

                .widget-header {
                    background: rgba(0, 0, 0, 0.4);
                    font-size: 15px;
                    padding-left: 5px;
                }

                .widget-content {
                    font-size: 20px;
                    font-weight: bold;
                    padding: 10px;
                }

                .btn-square:hover {
                    background: rgba(0, 0, 0, 0) !important;
                    box-shadow: 0 0 8px black;
                    -moz-box-shadow: 0 0 8px black;
                    -webkit-box-shadow: 0 0 8px black;
                    color: white;
                }

                .btn-square {
                    background: rgba(0, 0, 0, 0); color: white;
                    margin-top: 40px;
                    max-width :200px;
                    min-height: 200px;
                    white-space: normal !important;
                    width: 100%;
                }

                .heart {
                    -ms-transform: rotate(7deg);
                    -webkit-transform: rotate(7deg);
                    transform: rotate(7deg);
                }
            </style>

            {% block stylesheets %}{% endblock stylesheets %}
        {% endcompress %}

        {% block base_keywords %}{% endblock base_keywords %}
        <link rel="shortcut icon" type="image/png" href="{% static 'core/images/favicon.ico' %}" />
    </head>
    <body>
        <nav class="navbar navbar-inverse" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-navigation">
                        <span class="sr-only">{% trans 'Toggle navigation' %}</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'common:home_view' %}">{% project_name %}</a>
                </div>

                <div class="collapse navbar-collapse" id="main-navigation">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'common:about_view' %}">{% trans 'About' %}</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="icon-cog"></i>
                                {% trans 'Hello' %}:
                                {% if user.is_anonymous %}
                                    <span>{% trans "Anonymous" %}</span>
                                    <input type="hidden" id="auth_user" value="" />
                                {% else %}
                                    <span>{{ user }}</span>
                                    <input type="hidden" id="auth_user" value="{{ user }}" />
                                {% endif %}
                                 <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                {% if user.is_staff %}
                                    <li><a href="/admin/">{% trans 'Setup' %}</a></li>
                                {% endif %}

                                {% if user.is_anonymous %}
                                    <li><a href="{% url 'common:login_view' %}">{% trans 'Login' %}</a></li>
                                {% else %}
                                    <li><a href="{% url 'common:logout_view' %}">{% trans 'Logout' %}</a></li>
                                {% endif %}
                            </ul>
                        </li>
                    </ul>

                </div>


            </div>
        </nav>

        <div class="container">
            {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>{{ message }}</strong>
                </div>
            {% endfor %}

        </div>

        {% block content %}{% endblock content %}

        {% compress js %}
            <script src="{% static 'core/packages/jquery-2.1.1.min.js' %}"></script>
            <script src="{% static 'core/packages/bootstrap-3.2.0-dist/js/bootstrap.min.js' %}"></script>
            {% block javascript %}{% endblock javascript %}
        {% endcompress %}
    </body>
</html>

descartes_bi/apps/core/templates/core/login.html
{% load i18n %}
{% load static %}

{% load autoadmin_tags %}
{% load project_tags %}

{% load compress %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <title>{% project_name %}:: {% trans 'Login' %}</title>

        {% compress css %}
            <link href="{% static 'core/packages/bootstrap-3.2.0-dist/css/bootstrap.min.css' %}" rel="stylesheet">
            <link href="{% static 'core/packages/font-awesome-4.1.0/css/font-awesome.min.css' %}" rel="stylesheet">
            <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
            <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
            <!--[if lt IE 9]>
              <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
              <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
            <![endif]-->

            <link href="//fonts.googleapis.com/css?family=Raleway:100,200,300,400,500,600,700,800,900" rel="stylesheet" type="text/css">

            <style type="text/css">
                html {
                    background: url("{% static 'core/images/backgrounds/minimalistic_violet_purple_blue_artwallpaperhi_com.jpg' %}") no-repeat center center fixed;
                    -webkit-background-size: cover;
                    -moz-background-size: cover;
                    -o-background-size: cover;
                    background-size: cover;
                    color: white;
                    text-shadow: 0 0 3px rgba(255, 255, 255, 0.3);
                }

                body {
                    background: rgba(0, 0, 0, 0);
                    color: white;
                    text-shadow: 0 0 3px rgba(255, 255, 255, 0.3);
                    font-family: 'Raleway';
                }

                .modal-content {
                    background: rgba(0, 0, 0, 0.1);
                }

                .form-control {
                    background: rgba(0, 0, 0, 0);
                    color: white;
                }

                .form-control::-moz-placeholder {
                  color: rgba(255, 255, 255, 0.5);
                }

                .form-control:-ms-input-placeholder {
                  color: rgba(255, 255, 255, 0.5);
                }

                .form-control::-webkit-input-placeholder {
                  color: rgba(255, 255, 255, 0.5);
                }

                textarea:focus, input[type="text"]:focus, input[type="password"]:focus, input[type="datetime"]:focus, input[type="datetime-local"]:focus, input[type="date"]:focus, input[type="month"]:focus, input[type="time"]:focus, input[type="week"]:focus, input[type="number"]:focus, input[type="email"]:focus, input[type="url"]:focus, input[type="search"]:focus, input[type="tel"]:focus, input[type="color"]:focus, .uneditable-input:focus {
                    border-color: rgba(255, 255, 0, 0.8);
                    box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset, 0 0 8px rgba(255, 255, 0, 0.6);
                    outline: 0 none;
                }

                .modal-footer { border-top: 0px; }

                .modal-header {
                    border-bottom: 1px solid rgba(255, 255, 255, 0.6);
                }

                .panel {
                    background: rgba(0, 0, 0, 0.1);
                    border: 1px solid rgba(0, 0, 0, 0.2);
                    box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset, 0 0 8px rgba(0, 0, 0, 0.6);
                }

                .panel-heading {
                    background-color: rgba(0, 0, 0, 0.1);
                    color: white;
                }

                .btn {
                    background: rgba(0, 0, 0, 0.1);
                    border: 1px solid rgba(0, 0, 0, 0.1);
                }

                .btn:hover {
                    background: rgba(255, 255, 255, 0.1);
                    border: 1px solid rgba(255, 255, 255, 0.1);
                }
            </style>
        {% endcompress %}
    </head>

    <body>
        {% autoadmin_properties %}
        {% if autoadmin_properties.account %}
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                        <br>
                        <div class="panel">
                            <div class="panel-heading">
                                <h3 class="panel-title">{% trans 'First time login' %}</h3>
                            </div>
                            <div class="panel-body">
                                <div class="content login">
                                    <p>{% trans 'You have just finished installing <strong>Descartes BI</strong>, congratulations!' %}</p>
                                    <p>{% trans 'Login using the following credentials:' %}</p>
                                    <p>{% blocktrans with autoadmin_properties.account as account %}Username: <strong>{{ account }}</strong>{% endblocktrans %}</p>
                                    <p>{% blocktrans with autoadmin_properties.account.email as email %}Email: <strong>{{ email }}</strong>{% endblocktrans %}</p>
                                    <p>{% blocktrans with autoadmin_properties.password as password %}Password: <strong>{{ password }}</strong>{% endblocktrans %}</p>
                                    <p>{% trans 'Be sure to change the password to increase security and to disable this message.' %}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}


        <div id="loginModal" class="" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h1 class="text-center">{% trans 'Login' %}</h1>
                    </div>
                    {{ form.non_field_errors }}

                    <div class="modal-body">
                        <form class="form col-md-12 center-block" action="#" method="post">{% csrf_token %}
                            <div class="form-group">
                                {{ form.username.errors }}
                                <input type="text" class="form-control input-lg" id="username" name="username" placeholder="{% trans 'Username' %}">
                            </div>
                            <div class="form-group">
                                {{ form.password.errors }}
                                <input type="password" class="form-control input-lg" id="password" name="password" placeholder="{% trans 'Password' %}">
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary btn-lg btn-block">{% trans 'Sign In' %}</button>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <div class="col-md-12">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <script src="{% static 'core/packages/bootstrap-3.2.0-dist/js/bootstrap.min.js' %}"></script>
    </body>
</html>

descartes_bi/apps/core/templates/core/password_change_done.html
{% load i18n %}

{% with 'Alert' as title %}
{% with 'Your password has been changed successfully' as message %}
    {% include 'messagebox-attention.html' %}
{% endwith %}
{% endwith %}

descartes_bi/apps/core/templates/core/password_change_form.html
{% load i18n %}

{% if form.errors %}
    <div><div class="errorlist"></div></div>
    {% with 'Error' as title %}
    {% with 'An error has ocurred, try again.' as message %}
        {% include 'messagebox-error.html' %}
    {% endwith %}
    {% endwith %}
{% endif %}

<form class="login_panel_form" class="clearfix" action="{% url 'my_password_change' %}" method="post">
    {% csrf_token %}
    <input type="hidden" id="_wrapper" value="#login_form_wrapper" />
    <input type="hidden" id="_next_url" value="{% url 'my_password_change' %}" />
    <input type="hidden" id="_reload_window" value="1" />

    <h1 class="padlock">{% trans 'Change password' %}</h1>
    <label class="grey" for="log">{% trans 'Previous password' %}:</label>
    <input class="field" type="password" name="old_password" id="id_old_password" />
    <label class="grey" for="pwd">{% trans 'New password' %}:</label>
    <input class="field" type="password" name="new_password1" id="id_new_password1" />
    <label class="grey" for="pwd">{% trans 'Confirm new password' %}:</label>
    <input class="field" type="password" name="new_password2" id="id_new_password2" />

    <div class="clear"></div>
    <input type="submit" name="submit" value="{% trans 'Change' %}" class="bt_register" />
</form>