descartes_bi/apps/common/urls.py
from django.conf import settings
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from django.views.generic.base import RedirectView

from .views import AboutView, HomeView

urlpatterns = patterns('common.views',
    url(r'^$', login_required(HomeView.as_view()), name='home_view'),
    url(r'^set_language/$', 'set_language', name='set_language'),
    url(r'^about/$', login_required(AboutView.as_view()), name='about_view'),
)

urlpatterns += patterns('',
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'core/login.html'}, name='login_view'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': 'common:home_view'}, name='logout_view'),
    url(r'^myaccount/password_change/$', 'django.contrib.auth.views.password_change', {'template_name': 'core/password_change_form.html'}, name='password_change_view'),
    url(r'^accounts/password_change_ok/$', 'django.contrib.auth.views.password_change_done', {'template_name': 'core/password_change_done.html'}),

    (r'^favicon\.ico$', RedirectView.as_view(url='%simages/favicon.png' % settings.STATIC_URL)),
)

descartes_bi/apps/dashboards/urls.py
from __future__ import absolute_import

from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from .views import DashboardDetailView, DashboardListView

urlpatterns = patterns('',
    url(r'^$', login_required(DashboardListView.as_view()), name='dashboard_list'),
    url(r'^(?P<pk>\d+)/$', login_required(DashboardDetailView.as_view()), name='dashboard_view'),
)

descartes_bi/apps/widgets/urls.py
from __future__ import absolute_import

from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from .views import WidgetRenderView

urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)/$', login_required(WidgetRenderView.as_view()), name='widget_render'),
)

descartes_bi/urls.py
from django.conf.urls import include, patterns, url
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

handler500 = 'common.views.error500'
urlpatterns = patterns('',
    (r'^', include('common.urls', namespace='common')),
    (r'^admin/', include(admin.site.urls)),
    (r'^dashboards/', include('dashboards.urls', namespace='dashboards')),
    (r'^widgets/', include('widgets.urls', namespace='widgets')),
)

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    if 'rosetta' in settings.INSTALLED_APPS:
        urlpatterns += patterns('',
            url(r'^rosetta/', include('rosetta.urls'), name='rosetta'),
        )

descartes_bi/apps/dashboards/models.py
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from .literals import DEFAULT_ELEMENT_HEIGHT
from .managers import DashboardElementManager

from widgets.models import WidgetBase


@python_2_unicode_compatible
class Dashboard(models.Model):
    label = models.CharField(max_length=96, verbose_name=_('Label'))
    description = models.TextField(blank=True, verbose_name=_('Description'))
    enabled = models.BooleanField(default=True, verbose_name=_('Enabled'))
    full_screen = models.BooleanField(default=False, verbose_name=_('Full screen'))
    order = models.PositiveIntegerField(blank=True, null=True, default=0, verbose_name=_('Order'))

    def __str__(self):
        return self.label

    def get_absolute_url(self):
        return reverse('dashboards:dashboard_view', args=[str(self.pk)])

    def get_element_rows(self):
        rows = []
        row = []
        spans = 0
        for element in self.elements.enabled():
            spans += element.span
            if spans > 12:
                rows.append(row)
                spans = element.span
                row = []

            row.append(element)

        if row:
            rows.append(row)

        return rows

    class Meta:
        ordering = ('order',)
        verbose_name = _('Dashboard')
        verbose_name_plural = _('Dashboards')


@python_2_unicode_compatible
class DashboardElement(models.Model):
    dashboard = models.ForeignKey(Dashboard, verbose_name=_('Dashboard'), related_name='elements')
    enabled = models.BooleanField(default=True, verbose_name=_('Enabled'))
    span = models.PositiveIntegerField(help_text=_('The amount of columns in a 12 columns layout that this element should occupy.'), verbose_name=_('Span'))
    height = models.PositiveIntegerField(default=DEFAULT_ELEMENT_HEIGHT, verbose_name=_('Height'))
    order = models.PositiveIntegerField(blank=True, null=True, default=0, verbose_name=_('Order'))
    widget = models.ForeignKey(WidgetBase, verbose_name=_('Widget'))

    objects = DashboardElementManager()

    def __str__(self):
        return self.widget.label

    class Meta:
        verbose_name = _('Dashboard element')
        verbose_name_plural = _('Dashboard elements')
        ordering = ('order',)

descartes_bi/apps/dashboards/views.py
import logging

from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, ListView

from .models import Dashboard

logger = logging.getLogger(__name__)


class DashboardListView(ListView):
    context_object_name = 'dashboards'
    queryset = Dashboard.objects.filter(enabled=True)


class DashboardDetailView(DetailView):
    context_object_name = 'dashboard'
    model = Dashboard

descartes_bi/apps/dashboards/templates/dashboards/dashboard_detail.html
{% extends 'core/base.html' %}

{% load i18n %}
{% load static %}

{% block content %}
    <div class="container{% if dashboard.full_screen %}-fluid{% endif %}">
        {% for row in dashboard.get_element_rows %}
            <div class="row">
                {% for element in row %}
                    <div class="col-md-{{ element.span }}">
                        <div class="widget">
                            <div class="widget-header">
                                <span class="widget-label">{{ element }}</span>
                            </div>
                            <div class="widget-content" style="height: {{ element.height }}px;">
                                <div id="widget{{ element.pk }}" style="width: 100%; height: 100%;">
                                    <p class="text-center"><i class="refresh-spinner fa fa-cog fa-spin fa-3x"></i></p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
{% endblock content %}

{% block javascript %}
    <script type="text/javascript">
         $(document).ready(function() {
            {% for element in dashboard.elements.enabled %}
                $("#widget{{ element.pk }}").load("{% url 'widgets:widget_render' element.widget.pk %}?element_pk={{ element.pk }}");
            {% endfor %}
         });
    </script>
{% endblock javascript %}

descartes_bi/apps/dashboards/templates/dashboards/dashboard_list.html
{% extends 'core/base.html' %}
{% load i18n %}

{% block content %}
    <div class="container">
        <div class="row">
            {% for dashboard in dashboards %}
                <div class="col-md-4">
                    <p class="text-center">
                    <a class="btn btn-lg btn-default btn-square" href="{{ dashboard.get_absolute_url }}"><br> {{ dashboard }}<br><br><small>{{ dashboard.description }}</small></a>
                     </p>
                </div>
                {% if forloop.counter|divisibleby:3 %}
                    </div>
                    <div class="row">
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock content %}